# Generated by Django 4.2.5 on 2024-02-29 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='contect',
            new_name='content',
        ),
    ]
